- name: Create dbt Profile
        run: |
          mkdir -p ~/.dbt
          echo "olist:
            outputs:
              dev:
                type: postgres
                host: localhost
                user: postgres
                password: password
                port: 5432
                dbname: olist
                schema: public
                threads: 1
            target: dev" > ~/.dbt/profiles.yml

      - name: Run dbt Tests
        env:
          DBT_PROFILES_DIR: ~/.dbt
        run: |
          # If your dbt files are in a subfolder, add 'cd folder_name &&' before dbt
          dbt deps
          dbt test
